<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Unitsection;


class InsertSection extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'create:section';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'creating section list';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $array = [
            ["code" => "S01", "abr" => "HPN-PS", "name" => "HPN PERSONAL STAFF", "updated_by" => null],
            ["code" => "S02", "abr" => "HPN-CS", "name" => "HPN COORDINATING STAFF", "updated_by" => null],
            ["code" => "S03", "abr" => "HPN-TS", "name" => "HPN TECHNICAL STAFF", "updated_by" => null],
            ["code" => "S04", "abr" => "HPN-SS", "name" => "HPN SPECIAL STAFF", "updated_by" => null],
            ["code" => "S05", "abr" => "HPN-SSU", "name" => "SERVICE SUPPORT UNIT", "updated_by" => null],
            ["code" => "S06", "abr" => "HPF", "name" => "HEADQUARTERS PHILIPPINE FLEET", "updated_by" => null],
            ["code" => "S07", "abr" => "FTDC", "name" => "FLEET TRAINING AND DOCTRINES CENTER", "updated_by" => null],
            ["code" => "S08", "abr" => "FSG", "name" => "FLEET SUPPORT GROUP", "updated_by" => null],
            ["code" => "S09", "abr" => "LCF", "name" => "LITTORAL COMBAT FORCE", "updated_by" => null],
            ["code" => "S10", "abr" => "NAW", "name" => "NAVAL AIR WING", "updated_by" => null],
            ["code" => "S11", "abr" => "OCF", "name" => "OFFSHORE COMBAT FORCE", "updated_by" => null],
            ["code" => "S12", "abr" => "SAF", "name" => "SEALIFT AMPHIBIOUS FORCE", "updated_by" => null],
            ["code" => "S13", "abr" => "SUBGROUP", "name" => "SUBMARINE GROUP", "updated_by" => null],
            ["code" => "S14", "abr" => "MBde1", "name" => "MARINE BRIGADE 1", "updated_by" => null],
            ["code" => "S15", "abr" => "MBde2", "name" => "MARINE BRIGADE 2", "updated_by" => null],
            ["code" => "S16", "abr" => "MBde3", "name" => "MARINE BRIGADE 3", "updated_by" => null],
            ["code" => "S17", "abr" => "MBde4", "name" => "MARINE BRIGADE 4", "updated_by" => null],
            ["code" => "S18", "abr" => "MBN1", "name" => "MARINE BATTALION 1", "updated_by" => null],
            ["code" => "S19", "abr" => "MBN2", "name" => "MARINE BATTALION 2", "updated_by" => null],
            ["code" => "S20", "abr" => "MBN3", "name" => "MARINE BATTALION 3", "updated_by" => null],
            ["code" => "S21", "abr" => "MBN4", "name" => "MARINE BATTALION 4", "updated_by" => null],
            ["code" => "S22", "abr" => "MBN5", "name" => "MARINE BATTALION 5", "updated_by" => null],
            ["code" => "S23", "abr" => "MBN6", "name" => "MARINE BATTALION 6", "updated_by" => null],
            ["code" => "S24", "abr" => "MBN7", "name" => "MARINE BATTALION 7", "updated_by" => null],
            ["code" => "S25", "abr" => "MBN8", "name" => "MARINE BATTALION 8", "updated_by" => null],
            ["code" => "S26", "abr" => "MBN9", "name" => "MARINE BATTALION 9", "updated_by" => null],
            ["code" => "S27", "abr" => "MBN10", "name" => "MARINE BATTALION 10", "updated_by" => null],
            ["code" => "S28", "abr" => "MBN11", "name" => "MARINE BATTALION 11", "updated_by" => null],
            ["code" => "S29", "abr" => "MBN12", "name" => "MARINE BATTALION 12", "updated_by" => null],
            ["code" => "S30", "abr" => "FRG", "name" => "FORCE RECONNAISSANCE GROUP", "updated_by" => null],
            ["code" => "S31", "abr" => "CSBde", "name" => "COMBAT SUPPORT BRIGADE", "updated_by" => null],
            ["code" => "S32", "abr" => "AAR", "name" => "ASSAULT ARMOR REGIMENT", "updated_by" => null],
            ["code" => "S33", "abr" => "MAR", "name" => "MARINE ARTILLERY REGIMENT", "updated_by" => null],
            ["code" => "S34", "abr" => "SSR", "name" => "SERVICE SUPPORT REGIMENT", "updated_by" => null],
            ["code" => "S35", "abr" => "CDR", "name" => "COASTAL DEFENSE REGIMENT", "updated_by" => null],
            ["code" => "S36", "abr" => "HQBN", "name" => "HEADQUARTERS BATTALION", "updated_by" => null],
            ["code" => "S37", "abr" => "MCFDC", "name" => "MARINE CORPS DEVELOPMENT CENTER", "updated_by" => null],
            ["code" => "S38", "abr" => "MSEG", "name" => "MARINE SECURITY AND ESCORT GROUP", "updated_by" => null],
            ["code" => "S39", "abr" => "MBGL", "name" => "MARINE BASE GREGORIO LIM", "updated_by" => null],
            ["code" => "S40", "abr" => "MBAA", "name" => "MARINE BASE ARTHURO ASUNCION", "updated_by" => null],
            ["code" => "S41", "abr" => "PMCSC", "name" => "PMC SUPPLY CENTER", "updated_by" => null],
            ["code" => "S42", "abr" => "MCASU", "name" => "MARINE CORPS ADMINISTRATIVE SUPPORT UNIT", "updated_by" => null],
            ["code" => "S43", "abr" => "HFMRF", "name" => "HEADQUARTERS FLEET-MARINE READY FORCE", "updated_by" => null],
            ["code" => "S44", "abr" => "HSG", "name" => "HEADQUARTERS SUPPORT GROUP", "updated_by" => null],
            ["code" => "S45", "abr" => "NTGS", "name" => "NAVAL TASK GROUP - SEALION", "updated_by" => null],
            ["code" => "S46", "abr" => "NTGN", "name" => "NAVAL TASK GROUP - NCR", "updated_by" => null],
            ["code" => "S47", "abr" => "HNFW", "name" => "HEADQUARTERS NAVAL FORCES WEST", "updated_by" => null],
            ["code" => "S48", "abr" => "HNWM", "name" => "HEADQUARTERS NAVAL FORCES WESTERN MINDANAO", "updated_by" => null],
            ["code" => "S49", "abr" => "HNFNL", "name" => "HEADQUARTERS NAVAL FORCES NORTHERN LUZON", "updated_by" => null],
            ["code" => "S50", "abr" => "HNFEM", "name" => "HEADQUARTERS NAVAL FORCES EASTERN MINDANAO", "updated_by" => null],
            ["code" => "S51", "abr" => "HNFSL", "name" => "HEADQUARTERS NAVAL FORCES SOUTHERN LUZON", "updated_by" => null],
            ["code" => "S52", "abr" => "HNFC", "name" => "HEADQUARTERS NAVAL FORCES CENTRAL", "updated_by" => null],
            ["code" => "S53", "abr" => "HNAEC", "name" => "HEADQUARTERS NAVAL AMMUNITION AND EXPLOSIVE CENTER", "updated_by" => null],
            ["code" => "S54", "abr" => "HSSG", "name" => "HEADQUARTERS SERVICE SUPPORT GROUP", "updated_by" => null],
            ["code" => "S55", "abr" => "CBNRE", "name" => "CHEMICAL BIOLOGICAL RADIOLOGICAL NUCLEAR AND EXPLOSIVE DIVISION", "updated_by" => null],
            ["code" => "S56", "abr" => "NAEDCav", "name" => "NAVAL AMMUNITION AND EXPLOSIVE DEPOT CAVITE", "updated_by" => null],
            ["code" => "S57", "abr" => "NAEDCab", "name" => "NAVAL AMMUNITION AND EXPLOSIVE DEPOT CABALLO", "updated_by" => null],
            ["code" => "S58", "abr" => "NAEDD", "name" => "NAVAL AMMUNITION AND EXPLOSIVE DISTRIBUTION DIVISION", "updated_by" => null],
            ["code" => "S59", "abr" => "NAETD", "name" => "NAVAL AMMUNITION AND EXPLOSIVE TRAINING DIVISION", "updated_by" => null],
            ["code" => "S60", "abr" => "PTOD", "name" => "PORT TERMINAL OPERATIONS DIVISION", "updated_by" => null],
            ["code" => "S61", "abr" => "RND", "name" => "RESEARCH AND DEVELOPMENT DIVISION", "updated_by" => null],
            ["code" => "S62", "abr" => "NAEDEPOT", "name" => "NAVAL AMMUNITION AND EXPLOSIVE DEPOT", "updated_by" => null],
            ["code" => "S63", "abr" => "HNISF", "name" => "HEADQUARTERS NAVAL INTELLIGENCE AND SECURITY FORCE", "updated_by" => null],
            ["code" => "S64", "abr" => "MRIC", "name" => "MARITIME RESEARCH INFORMATION CENTER", "updated_by" => null],
            ["code" => "S65", "abr" => "TIG", "name" => "TECHNICAL INTELLIGENCE GROUP", "updated_by" => null],
            ["code" => "S66", "abr" => "TCG", "name" => "TRADECRAFT GROUP", "updated_by" => null],
            ["code" => "S67", "abr" => "AIG", "name" => "AFLOAT INTELLIGENCE GROUP", "updated_by" => null],
            ["code" => "S68", "abr" => "CIG", "name" => "COUNTERINTELLIGENCE GROUP", "updated_by" => null],
            ["code" => "S69", "abr" => "NISG8", "name" => "NAVAL INTELLIGENCE AND SECURITY GROUP 8", "updated_by" => null],
            ["code" => "S70", "abr" => "NISGS", "name" => "NAVAL INTELLIGENCE AND SECURITY GROUP x 7", "updated_by" => null],
            ["code" => "S71", "abr" => "HSG", "name" => "HEADQUARTERS SUPPORT GROUP", "updated_by" => null],
            ["code" => "S72", "abr" => "NITI", "name" => "NAVAL INTELLIGENCE TRAINING INSTITUTE", "updated_by" => null],
            ["code" => "S73", "abr" => "HNICTC", "name" => "HEADQUARTERS NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY CENTER", "updated_by" => null],
            ["code" => "S74", "abr" => "CSG", "name" => "CYBER SECURITY GROUP", "updated_by" => null],
            ["code" => "S75", "abr" => "ISG", "name" => "INFORMATION SYSTEMS GROUP", "updated_by" => null],
            ["code" => "S76", "abr" => "CTG", "name" => "COMMUNICATIONS TECHNOLOGY GROUP", "updated_by" => null],
            ["code" => "S77", "abr" => "MDAG", "name" => "MARITIME DOMAIN AND AWARENESS GROUP", "updated_by" => null],
            ["code" => "S78", "abr" => "IKMG", "name" => "INFORMATION-COMMS KNOWLEDGE AND MANAGEMENT GROUP", "updated_by" => null],
            ["code" => "S79", "abr" => "SSG", "name" => "SERVICE SUPPORT GROUP", "updated_by" => null],
            ["code" => "S80", "abr" => "NICTC MLA", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION MANILA", "updated_by" => null],
            ["code" => "S81", "abr" => "NICTC BNS", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION BONIFACIO", "updated_by" => null],
            ["code" => "S82", "abr" => "NICTC CAVITE", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION CAVITE", "updated_by" => null],
            ["code" => "S83", "abr" => "NICTC LA UNIION", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION LA UNION", "updated_by" => null],
            ["code" => "S84", "abr" => "NICTC ZAMBALES", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION ZAMBALES", "updated_by" => null],
            ["code" => "S85", "abr" => "NICTC CEBU", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION CEBU", "updated_by" => null],
            ["code" => "S86", "abr" => "NICTC DAVAO", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION DAVAO", "updated_by" => null],
            ["code" => "S87", "abr" => "NICTC LEGAZPI", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION LEGAZPI", "updated_by" => null],
            ["code" => "S88", "abr" => "NICTC PALAWAN", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION PALAWAN", "updated_by" => null],
            ["code" => "S89", "abr" => "NICTC ZAMBOANGA", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY STATION ZAMBOANGA", "updated_by" => null],
            ["code" => "S90", "abr" => "NICTC SANGLEY", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY UNIT SANGLEY", "updated_by" => null],
            ["code" => "S91", "abr" => "NICTU ULUGAN", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY UNIT ULUGAN", "updated_by" => null],
            ["code" => "S92", "abr" => "NICTU CAGAYAN", "name" => "NAVAL INFORMATION AND COMMUNICATION TECHNOLOGY UNIT CAGAYAN", "updated_by" => null],
            ["code" => "S93", "abr" => "LMS", "name" => "35 LITTORAL MONITORING STATION", "updated_by" => null],
            ["code" => "S94", "abr" => "TARS", "name" => "TETHERED AEROSTAT RADAR SYSTEM", "updated_by" => null],
            ["code" => "S95", "abr" => "HQS", "name" => "HEADQUARTERS NAVAL COMBAT ENGINEERING BRIGADE", "updated_by" => null],
            ["code" => "S96", "abr" => "1NWCB", "name" => "FIRST NAVAL WATERFRONT CONSTRUCTION BATTALION", "updated_by" => null],
            ["code" => "S97", "abr" => "2NMCB", "name" => "SECOND NAVAL MOBILE CONSTRUCTION BATTALION", "updated_by" => null],
            ["code" => "S98", "abr" => "3NCRB", "name" => "THIRD NAVAL COMBAT ENGINEERING BATTALION", "updated_by" => null],
            ["code" => "S99", "abr" => "4SSB", "name" => "FOURTH SERVICE SUPPORT BATTALION", "updated_by" => null],
            ["code" => "S100", "abr" => "BTDC", "name" => "BRIGADE TRAINING AND DOCTRINE CENTER", "updated_by" => null],
            ["code" => "S101", "abr" => "FPDC", "name" => "FACILITY PLANNING AND DESIGN CENTER", "updated_by" => null],
            ["code" => "S102", "abr" => "HCMOG", "name" => "HEADQUARTERS CIVIL MILITARY OPERATIONS GROUP-PN (HCMOG-PN)", "updated_by" => null],
            ["code" => "S103", "abr" => "HSU", "name" => "HEADQUARTERS SERVICE UNIT (HSU)", "updated_by" => null],
            ["code" => "S104", "abr" => "ISAU", "name" => "INFORMATION SUPPORT AFFAIRS UNIT", "updated_by" => null],
            ["code" => "S105", "abr" => "CAU", "name" => "CIVIL AFFAIRS UNIT", "updated_by" => null],
            ["code" => "S106", "abr" => "PAU", "name" => "PUBLIC AFFAIRS UNIT", "updated_by" => null],
            ["code" => "S107", "abr" => "CMOS", "name" => "CIVIL MILITARY OPERATIONS SCHOOL", "updated_by" => null],
            ["code" => "S108", "abr" => "CMOU", "name" => "CIVIL MILITARY OPERATIONS UNIT", "updated_by" => null],
            ["code" => "S109", "abr" => "HHSU", "name" => "HEADQUARTERS NAVAL SPECIAL OPERATIONS COMMAND", "updated_by" => null],
            ["code" => "S110", "abr" => "SEALG", "name" => "SEA-AIR-LAND GROUP", "updated_by" => null],
            ["code" => "S111", "abr" => "EODG", "name" => "NAVAL EXPLOSIVE ORDNANCE DISPOSAL GROUP", "updated_by" => null],
            ["code" => "S112", "abr" => "SBG", "name" => "SPECIAL BOAT GROUP", "updated_by" => null],
            ["code" => "S113", "abr" => "NDG", "name" => "NAVAL DIVING GROUP", "updated_by" => null],
            ["code" => "S114", "abr" => "CSSG", "name" => "COMBAT SERVICE SUPPORT GROUP", "updated_by" => null],
            ["code" => "S115", "abr" => "NSOU1", "name" => "NAVAL SPECIAL OPERATIONS UNIT 1", "updated_by" => null],
            ["code" => "S116", "abr" => "NSOU2", "name" => "NAVAL SPECIAL OPERATIONS UNIT 2", "updated_by" => null],
            ["code" => "S117", "abr" => "NSOU3", "name" => "NAVAL SPECIAL OPERATIONS UNIT 3", "updated_by" => null],
            ["code" => "S118", "abr" => "NSOU4", "name" => "NAVAL SPECIAL OPERATIONS UNIT 4", "updated_by" => null],
            ["code" => "S119", "abr" => "NSOU5", "name" => "NAVAL SPECIAL OPERATIONS UNIT 5", "updated_by" => null],
            ["code" => "S120", "abr" => "NSOU6", "name" => "NAVAL SPECIAL OPERATIONS UNIT 6", "updated_by" => null],
            ["code" => "S121", "abr" => "NSOU7", "name" => "NAVAL SPECIAL OPERATIONS UNIT 7", "updated_by" => null],
            ["code" => "S122", "abr" => "NSOU8", "name" => "NAVAL SPECIAL OPERATIONS UNIT 8", "updated_by" => null],
            ["code" => "S123", "abr" => "NSOU9", "name" => "NAVAL SPECIAL OPERATIONS UNIT 9", "updated_by" => null],
            ["code" => "S124", "abr" => "NSOU10", "name" => "NAVAL SPECIAL OPERATIONS UNIT 10", "updated_by" => null],
            ["code" => "S125", "abr" => "NSOU11", "name" => "NAVAL SPECIAL OPERATIONS UNIT 11", "updated_by" => null],
            ["code" => "S126", "abr" => "NSOTRDC", "name" => "NAVAL SPECIAL OPERATIONS TRAINING RESEARCH AND DOCTRINE CENTER", "updated_by" => null],
            ["code" => "S127", "abr" => "NMOC", "name" => "NAVAL METEROLOGICAL AND OCEANOGRAPHIC CENTER", "updated_by" => null],
            ["code" => "S128", "abr" => "HNMOC", "name" => "HEADQUARTERS NAVAL METEROLOGICAL AND OCEANOGRAPHIC CENTER", "updated_by" => null],
            ["code" => "S129", "abr" => "RER", "name" => "RESEARCH AND EXTERNAL RELATIONS (INTER-AGENCY)", "updated_by" => null],
            ["code" => "S130", "abr" => "SCP", "name" => "SURVEY COLLECTION AND PROCESSING", "updated_by" => null],
            ["code" => "S131", "abr" => "GSD", "name" => "GENERAL SERVICE DEPARTMENT", "updated_by" => null],
            ["code" => "S132", "abr" => "METOC", "name" => "METOC SCHOOL", "updated_by" => null],
            ["code" => "S133", "abr" => "PAD", "name" => "PRINTING AND DISTRIBUTION", "updated_by" => null],
            ["code" => "S134", "abr" => "HNSSC", "name" => "HEADQUARTERS NAVAL SEA SYSTEMS COMMAND", "updated_by" => null],
            ["code" => "S135", "abr" => "NSSTC", "name" => "NAVAL SEA SYSTEMS TRAINING CENTER", "updated_by" => null],
            ["code" => "S136", "abr" => "NRTDC", "name" => "NAVAL RESEARCH TECHNOLOGY & DEVELOPMENT CENTER", "updated_by" => null],
            ["code" => "S137", "abr" => "NSSC", "name" => "NAVAL SYSTEMS SUPPORT FACILITY", "updated_by" => null],
            ["code" => "S138", "abr" => "NILMC", "name" => "NAVAL INTERMEDIATE LEVEL MAINTENANCE CENTER", "updated_by" => null],
            ["code" => "S139", "abr" => "HNCSC", "name" => "NAVAL COMBAT SYSTEMS CENTER", "updated_by" => null],
            ["code" => "S140", "abr" => "HNS", "name" => "HEADQUARTERS NAVAL SHIPYARD", "updated_by" => null],
            ["code" => "S141", "abr" => "HNIC", "name" => "HEADQUARTERS NAVAL INSTALLATION COMMAND", "updated_by" => null],
            ["code" => "S142", "abr" => "ICTS", "name" => "INSTALLATION COMMAND TRAINING SCHOOL", "updated_by" => null],
            ["code" => "S143", "abr" => "HNLC", "name" => "HEADQUARTERS NAVAL LOGISTIC CENTER", "updated_by" => null],
            ["code" => "S144", "abr" => "HSSG", "name" => "HEADQUARTERS SERVICE SUPPORT GROUP", "updated_by" => null],
            ["code" => "S145", "abr" => "SDD", "name" => "SUPPLY DISTRIBUTION DIVISION", "updated_by" => null],
            ["code" => "S146", "abr" => "RSD", "name" => "READY STORE DIVISION", "updated_by" => null],
            ["code" => "S147", "abr" => "DISP", "name" => "DISPOSAL DIVISION", "updated_by" => null],
            ["code" => "S148", "abr" => "PTOG", "name" => "PORT TERMINAL OPERATIONS GROUP", "updated_by" => null],
            ["code" => "S149", "abr" => "NLETS", "name" => "NAVAL LOGISTICS EDUCATION AND TRAINING SCHOOL", "updated_by" => null],
            ["code" => "S150", "abr" => "NPD", "name" => "NAVAL PETROLEUM DEPOT", "updated_by" => null],
            ["code" => "S151", "abr" => "HNETDC", "name" => "HEADQUARTERS NAVAL EDUCATION", "updated_by" => null],
            ["code" => "S152", "abr" => "NOSC", "name" => "NAVAL OFFICERS SCHOOLS CENTER", "updated_by" => null],
            ["code" => "S153", "abr" => "NEPSC", "name" => "NAVAL ENLISTED PERSONNEL SCHOOLS CENTER", "updated_by" => null],
            ["code" => "S154", "abr" => "FMWC", "name" => "FLEET MARINE WARFARE CENTER", "updated_by" => null],
            ["code" => "S155", "abr" => "TDC", "name" => "TRAINING AND DEVELOPMENT CENTER", "updated_by" => null],
            ["code" => "S156", "abr" => "NLDC", "name" => "NAVAL LEADERSHIP DEVELOPMENT CENTER", "updated_by" => null],
            ["code" => "S157", "abr" => "NPMC", "name" => "NAVY PERSONNEL MANAGEMENT CENTER", "updated_by" => null],
            ["code" => "S158", "abr" => "HPNFC", "name" => "HEADQUARTERS PHILIPPINE NAVY FINANCE CENTER", "updated_by" => null],
            ["code" => "S159", "abr" => "HSU", "name" => "HEADQUARTERS SERVICE UNIT", "updated_by" => null],
            ["code" => "S160", "abr" => "CPMU", "name" => "CENTRALIZED PAYROLL MANAGEMENT UNIT", "updated_by" => null],
            ["code" => "S161", "abr" => "FTU", "name" => "FINANCE TRAINING UNIT", "updated_by" => null],
            ["code" => "S162", "abr" => "DRU", "name" => "DISBURSEMENT AND REMITTANCE UNIT", "updated_by" => null],
            ["code" => "S163", "abr" => "NFSUA1", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)1", "updated_by" => null],
            ["code" => "S164", "abr" => "NFSUA2", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)2", "updated_by" => null],
            ["code" => "S165", "abr" => "NFSUA3", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)3", "updated_by" => null],
            ["code" => "S166", "abr" => "NFSUA4", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)4", "updated_by" => null],
            ["code" => "S167", "abr" => "NFSUA5", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)5", "updated_by" => null],
            ["code" => "S168", "abr" => "NFSUA6", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)6", "updated_by" => null],
            ["code" => "S169", "abr" => "NFSUA7", "name" => "NAVAL FINANCE SERVICE UNIT (Type A)7", "updated_by" => null],
            ["code" => "S170", "abr" => "NFSUB1", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)1", "updated_by" => null],
            ["code" => "S171", "abr" => "NFSUB2", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)2", "updated_by" => null],
            ["code" => "S172", "abr" => "NFSUB3", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)3", "updated_by" => null],
            ["code" => "S173", "abr" => "NFSUB4", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)4", "updated_by" => null],
            ["code" => "S174", "abr" => "NFSUB5", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)5", "updated_by" => null],
            ["code" => "S175", "abr" => "NFSUB6", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)6", "updated_by" => null],
            ["code" => "S176", "abr" => "NFSUB7", "name" => "NAVAL FINANCE SERVICE UNIT (Type B)7", "updated_by" => null],
            ["code" => "S177", "abr" => "HNRC", "name" => "HEADQUARTERS NAVAL RESERVE COMMAND", "updated_by" => null],
            ["code" => "S178", "abr" => "HSG", "name" => "HEADQUARTER SERVICE GROUP", "updated_by" => null],
            ["code" => "S179", "abr" => "NRMC", "name" => "NAVAL RESERVIST MANAGEMENT CENTER", "updated_by" => null],
            ["code" => "S180", "abr" => "NRCTC", "name" => "NAVAL RESERVE COMMAND TRAINING CENTER", "updated_by" => null],
            ["code" => "S181", "abr" => "NRCEN NL", "name" => "NAVAL RESERVE CENTER NORTHERN LUZON", "updated_by" => null],
            ["code" => "S182", "abr" => "NRCEN NCR", "name" => "NAVAL RESERVE CENTER NCR", "updated_by" => null],
            ["code" => "S183", "abr" => "NRCEN SL", "name" => "NAVAL RESERVE CENTER SOUTHERN LUZON", "updated_by" => null],
            ["code" => "S184", "abr" => "NRCEN WEST", "name" => "NAVAL RESERVE CENTER WEST", "updated_by" => null],
            ["code" => "S185", "abr" => "NRCEN WV", "name" => "NAVAL RESERVE CENTER WESTERN VISAYAS", "updated_by" => null],
            ["code" => "S186", "abr" => "NRC EV", "name" => "NAVAL RESERVE CENTER EASTERN VISAYAS", "updated_by" => null],
            ["code" => "S187", "abr" => "NRCEN WM", "name" => "NAVAL RESERVE CENTER WESTERN MINDANAO", "updated_by" => null],
            ["code" => "S188", "abr" => "NRCEN EM", "name" => "NAVAL RESERVE CENTER EASTERN MINDANAO", "updated_by" => null],
            ["code" => "S189", "abr" => "169NROTC", "name" => "169th NROTC  (Maritime Academy of Asia and the Pacific)", "updated_by" => null],
            ["code" => "S190", "abr" => "149NROTC", "name" => "149th NROTC (Philippine Merchant Maritime Academy)", "updated_by" => null],
            ["code" => "S191", "abr" => "NSDC", "name" => "NAVAL SUPPLY DEPOT CAVITE", "updated_by" => null],
            ["code" => "S192", "abr" => "NSDLU", "name" => "NAVAL SUPPLY DEPOT LA UNION", "updated_by" => null],
            ["code" => "S193", "abr" => "NSDL", "name" => "NAVAL SUPPLY DEPOT LEGAZPI", "updated_by" => null],
            ["code" => "S194", "abr" => "NSDP", "name" => "NAVAL SUPPLY DEPOT PALAWAN", "updated_by" => null],
            ["code" => "S195", "abr" => "NSDC", "name" => "NAVAL SUPPLY DEPOT CEBU", "updated_by" => null],
            ["code" => "S196", "abr" => "NSDZ", "name" => "NAVAL SUPPLY DEPOT ZAMBOANGA", "updated_by" => null],
            ["code" => "S197", "abr" => "NSDD", "name" => "NAVAL SUPPLY DEPOT DAVAO", "updated_by" => null],
            ["code" => "S198", "abr" => "NIF-CAVITE", "name" => "NIF - CAVITE", "updated_by" => null],
            ["code" => "S199", "abr" => "NIF-NCR", "name" => "NIF - NCR", "updated_by" => null],
            ["code" => "S200", "abr" => "NIF-NL", "name" => "NIF - NL", "updated_by" => null],
            ["code" => "S201", "abr" => "NIF-SL", "name" => "NIF - SL", "updated_by" => null],
            ["code" => "S202", "abr" => "NIF-WEST", "name" => "NIF - WEST", "updated_by" => null],
            ["code" => "S203", "abr" => "NIF-CENTRAL", "name" => "NIF - CENTRAL", "updated_by" => null],
            ["code" => "S204", "abr" => "NIF-EAST MIN", "name" => "NIF - EAST MIN", "updated_by" => null],
            ["code" => "S205", "abr" => "N-WM", "name" => "NIF - WEST MIN", "updated_by" => null],
            ["code" => "S206", "abr" => "NIF-WEST MIN", "name" => "NIF - WEST MIN", "updated_by" => null],
            ["code" => "S207", "abr" => "NIF-ZAMBALES", "name" => "NIF - ZAMBALES", "updated_by" => null]
        ];

        foreach ($array as $value) {
            Unitsection::create($value);
        }
    }
}
