<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Unitrelation;
class InsertRelation extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'create:relation';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $array = [
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T01", "code_rel" => "RE01", "office" => 1, "restrict" => 10, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T02", "code_rel" => "RE02", "office" => 1, "restrict" => 10, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T03", "code_rel" => "RE03", "office" => 1, "restrict" => 10, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T04", "code_rel" => "RE04", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T05", "code_rel" => "RE05", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T06", "code_rel" => "RE06", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T07", "code_rel" => "RE07", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T08", "code_rel" => "RE08", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T09", "code_rel" => "RE09", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T10", "code_rel" => "RE10", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S01", "team" => "T11", "code_rel" => "RE11", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T12", "code_rel" => "RE12", "office" => 1, "restrict" => 1, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T13", "code_rel" => "RE13", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T14", "code_rel" => "RE14", "office" => 1, "restrict" => 3, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T15", "code_rel" => "RE15", "office" => 1, "restrict" => 4, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T16", "code_rel" => "RE16", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T17", "code_rel" => "RE17", "office" => 1, "restrict" => 6, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T18", "code_rel" => "RE18", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T19", "code_rel" => "RE19", "office" => 1, "restrict" => 8, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T20", "code_rel" => "RE20", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T21", "code_rel" => "RE21", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S02", "team" => "T22", "code_rel" => "RE22", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S03", "team" => "T23", "code_rel" => "RE23", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S03", "team" => "T24", "code_rel" => "RE24", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S03", "team" => "T25", "code_rel" => "RE25", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S03", "team" => "T26", "code_rel" => "RE26", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S03", "team" => "T27", "code_rel" => "RE27", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S03", "team" => "T28", "code_rel" => "RE28", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T29", "code_rel" => "RE29", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T30", "code_rel" => "RE30", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T31", "code_rel" => "RE31", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T32", "code_rel" => "RE32", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T33", "code_rel" => "RE33", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T34", "code_rel" => "RE34", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T35", "code_rel" => "RE35", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T36", "code_rel" => "RE36", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S04", "team" => "T37", "code_rel" => "RE37", "office" => 1, "restrict" => null, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA01", "department" => "D01", "section" => "S05", "team" => "T38", "code_rel" => "RE38", "office" => 1, "restrict" => 3, "rights" => null, "hpn" => 1, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S06", "team" => null, "code_rel" => "RE39", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S07", "team" => null, "code_rel" => "RE40", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S08", "team" => null, "code_rel" => "RE41", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S09", "team" => null, "code_rel" => "RE42", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S10", "team" => null, "code_rel" => "RE43", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S11", "team" => null, "code_rel" => "RE44", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S12", "team" => null, "code_rel" => "RE45", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D02", "section" => "S13", "team" => null, "code_rel" => "RE46", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S14", "team" => null, "code_rel" => "RE47", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S15", "team" => null, "code_rel" => "RE48", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S16", "team" => null, "code_rel" => "RE49", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S17", "team" => null, "code_rel" => "RE50", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S18", "team" => null, "code_rel" => "RE51", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S19", "team" => null, "code_rel" => "RE52", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S20", "team" => null, "code_rel" => "RE53", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S21", "team" => null, "code_rel" => "RE54", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S22", "team" => null, "code_rel" => "RE55", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S23", "team" => null, "code_rel" => "RE56", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S24", "team" => null, "code_rel" => "RE57", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S25", "team" => null, "code_rel" => "RE58", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S26", "team" => null, "code_rel" => "RE59", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S27", "team" => null, "code_rel" => "RE60", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S28", "team" => null, "code_rel" => "RE61", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S29", "team" => null, "code_rel" => "RE62", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S30", "team" => null, "code_rel" => "RE63", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S31", "team" => null, "code_rel" => "RE64", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S32", "team" => null, "code_rel" => "RE65", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S33", "team" => null, "code_rel" => "RE66", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S34", "team" => null, "code_rel" => "RE67", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S35", "team" => null, "code_rel" => "RE68", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S36", "team" => null, "code_rel" => "RE69", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S37", "team" => null, "code_rel" => "RE70", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S38", "team" => null, "code_rel" => "RE71", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S39", "team" => null, "code_rel" => "RE72", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S40", "team" => null, "code_rel" => "RE73", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S41", "team" => null, "code_rel" => "RE74", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA02", "department" => "D03", "section" => "S42", "team" => null, "code_rel" => "RE75", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D04", "section" => "S43", "team" => null, "code_rel" => "RE76", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D04", "section" => "S44", "team" => null, "code_rel" => "RE77", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D04", "section" => "S45", "team" => null, "code_rel" => "RE78", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D04", "section" => "S46", "team" => null, "code_rel" => "RE79", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D05", "section" => "S47", "team" => null, "code_rel" => "RE80", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D06", "section" => "S48", "team" => null, "code_rel" => "RE81", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D07", "section" => "S49", "team" => null, "code_rel" => "RE82", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D08", "section" => "S50", "team" => null, "code_rel" => "RE83", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D09", "section" => "S51", "team" => null, "code_rel" => "RE84", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA03", "department" => "D10", "section" => "S52", "team" => null, "code_rel" => "RE85", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S53", "team" => null, "code_rel" => "RE86", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S54", "team" => null, "code_rel" => "RE87", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S55", "team" => null, "code_rel" => "RE88", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S56", "team" => null, "code_rel" => "RE89", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S57", "team" => null, "code_rel" => "RE90", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S58", "team" => null, "code_rel" => "RE91", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S59", "team" => null, "code_rel" => "RE92", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S60", "team" => null, "code_rel" => "RE93", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S61", "team" => null, "code_rel" => "RE94", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D11", "section" => "S62", "team" => null, "code_rel" => "RE95", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S63", "team" => null, "code_rel" => "RE96", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S64", "team" => null, "code_rel" => "RE97", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S65", "team" => null, "code_rel" => "RE98", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S66", "team" => null, "code_rel" => "RE99", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S67", "team" => null, "code_rel" => "RE100", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S68", "team" => null, "code_rel" => "RE101", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S69", "team" => null, "code_rel" => "RE102", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S70", "team" => null, "code_rel" => "RE103", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S71", "team" => null, "code_rel" => "RE104", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D12", "section" => "S72", "team" => null, "code_rel" => "RE105", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S73", "team" => null, "code_rel" => "RE106", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S74", "team" => null, "code_rel" => "RE107", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S75", "team" => null, "code_rel" => "RE108", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S76", "team" => null, "code_rel" => "RE109", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S77", "team" => null, "code_rel" => "RE110", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S78", "team" => null, "code_rel" => "RE111", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S79", "team" => null, "code_rel" => "RE112", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S80", "team" => null, "code_rel" => "RE113", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S81", "team" => null, "code_rel" => "RE114", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S82", "team" => null, "code_rel" => "RE115", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S83", "team" => null, "code_rel" => "RE116", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S84", "team" => null, "code_rel" => "RE117", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S85", "team" => null, "code_rel" => "RE118", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S86", "team" => null, "code_rel" => "RE119", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S87", "team" => null, "code_rel" => "RE120", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S88", "team" => null, "code_rel" => "RE121", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S89", "team" => null, "code_rel" => "RE122", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S90", "team" => null, "code_rel" => "RE123", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S91", "team" => null, "code_rel" => "RE124", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S92", "team" => null, "code_rel" => "RE125", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S93", "team" => null, "code_rel" => "RE126", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D13", "section" => "S94", "team" => null, "code_rel" => "RE127", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S95", "team" => null, "code_rel" => "RE128", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S96", "team" => null, "code_rel" => "RE129", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S97", "team" => null, "code_rel" => "RE130", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S98", "team" => null, "code_rel" => "RE131", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S99", "team" => null, "code_rel" => "RE132", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S100", "team" => null, "code_rel" => "RE133", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D14", "section" => "S101", "team" => null, "code_rel" => "RE134", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S102", "team" => null, "code_rel" => "RE135", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S103", "team" => null, "code_rel" => "RE136", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S104", "team" => null, "code_rel" => "RE137", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S105", "team" => null, "code_rel" => "RE138", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S106", "team" => null, "code_rel" => "RE139", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S107", "team" => null, "code_rel" => "RE140", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D15", "section" => "S108", "team" => null, "code_rel" => "RE141", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S109", "team" => null, "code_rel" => "RE142", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S110", "team" => null, "code_rel" => "RE143", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S111", "team" => null, "code_rel" => "RE144", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S112", "team" => null, "code_rel" => "RE145", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S113", "team" => null, "code_rel" => "RE146", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S114", "team" => null, "code_rel" => "RE147", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S115", "team" => null, "code_rel" => "RE148", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S116", "team" => null, "code_rel" => "RE149", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S117", "team" => null, "code_rel" => "RE150", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S118", "team" => null, "code_rel" => "RE151", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S119", "team" => null, "code_rel" => "RE152", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S120", "team" => null, "code_rel" => "RE153", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S121", "team" => null, "code_rel" => "RE154", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S122", "team" => null, "code_rel" => "RE155", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S123", "team" => null, "code_rel" => "RE156", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S124", "team" => null, "code_rel" => "RE157", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S125", "team" => null, "code_rel" => "RE158", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D16", "section" => "S126", "team" => null, "code_rel" => "RE159", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S127", "team" => null, "code_rel" => "RE160", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S128", "team" => null, "code_rel" => "RE161", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S129", "team" => null, "code_rel" => "RE162", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S130", "team" => null, "code_rel" => "RE163", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S131", "team" => null, "code_rel" => "RE164", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S132", "team" => null, "code_rel" => "RE165", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA04", "department" => "D17", "section" => "S133", "team" => null, "code_rel" => "RE166", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S134", "team" => null, "code_rel" => "RE167", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S135", "team" => null, "code_rel" => "RE168", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S136", "team" => null, "code_rel" => "RE169", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S137", "team" => null, "code_rel" => "RE170", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S138", "team" => null, "code_rel" => "RE171", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S139", "team" => null, "code_rel" => "RE172", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D18", "section" => "S140", "team" => null, "code_rel" => "RE173", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S141", "team" => "T39", "code_rel" => "RE174", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S142", "team" => "T40", "code_rel" => "RE175", "office" => 1, "restrict" => 13, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S143", "team" => null, "code_rel" => "RE176", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S144", "team" => null, "code_rel" => "RE177", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S145", "team" => null, "code_rel" => "RE178", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S146", "team" => null, "code_rel" => "RE179", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S147", "team" => null, "code_rel" => "RE180", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S148", "team" => null, "code_rel" => "RE181", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S149", "team" => null, "code_rel" => "RE182", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S150", "team" => null, "code_rel" => "RE183", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D21", "section" => "S151", "team" => null, "code_rel" => "RE184", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D21", "section" => "S152", "team" => null, "code_rel" => "RE185", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D21", "section" => "S153", "team" => null, "code_rel" => "RE186", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D21", "section" => "S154", "team" => null, "code_rel" => "RE187", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D21", "section" => "S155", "team" => null, "code_rel" => "RE188", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D21", "section" => "S156", "team" => null, "code_rel" => "RE189", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D22", "section" => "S157", "team" => null, "code_rel" => "RE190", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S158", "team" => null, "code_rel" => "RE191", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S159", "team" => null, "code_rel" => "RE192", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S160", "team" => null, "code_rel" => "RE193", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S161", "team" => null, "code_rel" => "RE194", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S162", "team" => null, "code_rel" => "RE195", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S163", "team" => null, "code_rel" => "RE196", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S164", "team" => null, "code_rel" => "RE197", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S165", "team" => null, "code_rel" => "RE198", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S166", "team" => null, "code_rel" => "RE199", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S167", "team" => null, "code_rel" => "RE200", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S168", "team" => null, "code_rel" => "RE201", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S169", "team" => null, "code_rel" => "RE202", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S170", "team" => null, "code_rel" => "RE203", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S171", "team" => null, "code_rel" => "RE204", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S172", "team" => null, "code_rel" => "RE205", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S173", "team" => null, "code_rel" => "RE206", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S174", "team" => null, "code_rel" => "RE207", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S175", "team" => null, "code_rel" => "RE208", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D23", "section" => "S176", "team" => null, "code_rel" => "RE209", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S177", "team" => null, "code_rel" => "RE210", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S178", "team" => null, "code_rel" => "RE211", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S179", "team" => null, "code_rel" => "RE212", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S180", "team" => null, "code_rel" => "RE213", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S181", "team" => null, "code_rel" => "RE214", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S182", "team" => null, "code_rel" => "RE215", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S183", "team" => null, "code_rel" => "RE216", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S184", "team" => null, "code_rel" => "RE217", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S185", "team" => null, "code_rel" => "RE218", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S186", "team" => null, "code_rel" => "RE219", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S187", "team" => null, "code_rel" => "RE220", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S188", "team" => null, "code_rel" => "RE221", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S189", "team" => null, "code_rel" => "RE222", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA06", "department" => "D24", "section" => "S190", "team" => null, "code_rel" => "RE223", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S191", "team" => null, "code_rel" => "RE224", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S192", "team" => null, "code_rel" => "RE225", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S193", "team" => null, "code_rel" => "RE226", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S194", "team" => null, "code_rel" => "RE227", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S195", "team" => null, "code_rel" => "RE228", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S196", "team" => null, "code_rel" => "RE229", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S197", "team" => null, "code_rel" => "RE230", "office" => null, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T41", "code_rel" => "RE231", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T42", "code_rel" => "RE232", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T43", "code_rel" => "RE233", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T44", "code_rel" => "RE234", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T45", "code_rel" => "RE235", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T46", "code_rel" => "RE236", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T47", "code_rel" => "RE237", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S198", "team" => "T48", "code_rel" => "RE238", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T49", "code_rel" => "RE239", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T50", "code_rel" => "RE240", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T51", "code_rel" => "RE241", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T52", "code_rel" => "RE242", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T53", "code_rel" => "RE243", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S199", "team" => "T54", "code_rel" => "RE244", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S200", "team" => "T55", "code_rel" => "RE245", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S200", "team" => "T56", "code_rel" => "RE246", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S200", "team" => "T57", "code_rel" => "RE247", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S200", "team" => "T58", "code_rel" => "RE248", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S201", "team" => "T59", "code_rel" => "RE249", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S201", "team" => "T60", "code_rel" => "RE250", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S202", "team" => "T61", "code_rel" => "RE251", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S202", "team" => "T62", "code_rel" => "RE252", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S202", "team" => "T63", "code_rel" => "RE253", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S202", "team" => "T64", "code_rel" => "RE254", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S202", "team" => "T65", "code_rel" => "RE255", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S203", "team" => "T66", "code_rel" => "RE256", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S203", "team" => "T67", "code_rel" => "RE257", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S203", "team" => "T68", "code_rel" => "RE258", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S203", "team" => "T69", "code_rel" => "RE259", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S204", "team" => "T70", "code_rel" => "RE260", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S204", "team" => "T71", "code_rel" => "RE261", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D20", "section" => "S205", "team" => null, "code_rel" => "RE262", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S206", "team" => "T72", "code_rel" => "RE263", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S206", "team" => "T73", "code_rel" => "RE264", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S206", "team" => "T74", "code_rel" => "RE265", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S206", "team" => "T75", "code_rel" => "RE266", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S207", "team" => "T76", "code_rel" => "RE267", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019],
            ["category" => "CA05", "department" => "D19", "section" => "S207", "team" => "T77", "code_rel" => "RE268", "office" => 1, "restrict" => null, "rights" => null, "hpn" => null, "org" => 2019]
        ];

        foreach ($array as $key => $value) {
            Unitrelation::create($value);
        }
    }
}
